version: '3'
services:
  gpt-neo-assistant:
    image: gpt-neo-assistant
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    stdin_open: true  
    tty: true         
    command: python ai_assistant.py